// export const ADD_CART_ITEM_REQUEST = "ADD_CART_ITEM_REQUEST";
// export const ADD_TO_CART = "ADD_CART_ITEM";
// export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
// export const FETCH_CART_ITEMS_REQUEST = "FETCH_CART_ITEMS_REQUEST";
// export const FETCH_CART_ITEMS = "FETCH_CART_ITEMS";
// export const FETCH_CART_ITEMS_FAIL = "FETCH_CART_ITEMS_FAIL";
// export const ADD = "ADD";
// export const SUB = "SUBTRACT";

// export const ADD_CART_ITEM_REQUEST = "ADD_CART_ITEM_REQUEST";
// export const ADD_CART_ITEM_SUCCESS = "ADD_CART_ITEM_SUCCESS";
// export const ADD_CART_ITEM_FAIL = "ADD_CART_ITEM_FAIL";
// export const FETCH_CART_ITEMS_REQUEST = "FETCH_CART_ITEMS_REQUEST";
// export const FETCH_CART_ITEMS_SUCCESS = "FETCH_CART_ITEMS_SUCCESS";
// export const FETCH_CART_ITEMS_FAIL = "FETCH_CART_ITEMS_FAIL";
// export const REMOVE_CART_ITEM_REQUEST = "REMOVE_CART_ITEM_REQUEST";
// export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS";
// export const REMOVE_CART_ITEM_FAIL = "REMOVE_CART_ITEM_FAIL";
// export const EMPTY_CART = "EMPTY_CART";

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
